spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://27.74.255.96:5431/english_master
    username: postgres
    password: meu@sds12@!#gh
  mail:
    host: smtp.gmail.com
    port: 587
    username: testmeusolution@gmail.com
    password: bopciqcccnuhoazn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true
        enable_lazy_load_no_trans: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

englishmaster:
  salt:
    hash:
      jwtToken: AHFUI@fh31ofhq94g42o4ngjsdnfksdjnuhsnkajngqwiue2n@IUBFIBb1hf13
  jwtSecret: MeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolution
  jwtExpiration: 259200000
  jwtRefreshExpirationMs: 259200000
  linkBE: https://gateway.dev.meu-solutions.com/englishmaster/api/v2/
  linkFE: https://englishmaster.erp.meu-solutions.com/
  fileSave: /home/git-ci/storge
  linkFileShowImageBE: https://gateway.dev.meu-solutions.com/englishmaster/api/v2/file/show/
  connect:
    student-nodejs: connect-student-nodejs.appspot.com

firebase:
  adminsdk:
    path: connect-student-nodejs-firebase-adminsdk-zo8a7-41168954b1.json

oxford:
  api:
    appId: b0d75c01
    appKey: b4c9785647f293f503eb45df46298c9d
    baseUrl: https://od-api.oxforddictionaries.com:443/api/v2

dictionary:
  api: https://api.dictionaryapi.dev/api/v2/entries/en
  file:
    path: english.txt

unsplash:
  api:
    key: s8Hd65PPMEIgtitVMXJJAcZzvVSiXI-q6qqx4M_PG7k

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /englishmaster/api/v2/v3/api-docs
    config-url: /englishmaster/api/v2/v3/api-docs/swagger-config
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  paths-to-match: /api/**

app:
  api:
    endpoint:
      prefix: /api/v2

server:
  forward-headers-strategy: framework

upload:
  server:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXQiOiJtZXVlbmdsaXNoIiwiaWF0IjoxNTE2MjM5MDIyfQ.jIAXLrrGhQseo8iZ6CNhXjf1Izs_nOK_RrcndzHYhJE18w0nPsx3PaHkG52zTARDWYasosOvTps_h_8-IAQ2FDZXgb2F5IhAukbDDEM7yL7bBtpZrgPnybbhu4TFcGMeealUvatifU1LUEKardPe62b12SdEiUkmag9lIjD81vBZ2KSAYJAFVchQ012dOPzT-O7qg2uBvfc-1XwKHBW5emMCEmlJh_DZ-rORSPvLpXzau9nhELAP9Hg-MCipmhhHR_4iaxX1ljhe4mq3T8rva86sLVDnOVzVB6I_Yl5S5zo2CCVM-5StxkAQABHtHzGeFsPYeHwK0ySwbYYHVF01lw
    api:
      upload: https://meuupload.meu-solutions.com/api/v1.0/upload/single/
      delete: https://meuupload.meu-solutions.com/api/v1.0/upload/

cloudinary:
  cloud-name: dxioq4art
  api-key: 583938679842993
  api-secret: ZD545JfRsmG1wcwFwmOoN8VgcU0

assembly:
  api-key: 845b5a3c7bf342b38fb7a180998f33f5
  transcribe-audio:
    endpoint: https://api.assemblyai.com/v2/transcript
  transcript:
    endpoint: https://api.assemblyai.com/v2/transcript/:transcript_id

cohere:
  api-key: VWeJEIJZmM301ej796csMwqQp2U2eTdabvSp0ULw
  chat-endpoint: https://api.cohere.com/v2/chat
  chat-model: command-a-03-2025

link:
  fe:
    mock-test:
      result:
        speaking: https://englishmaster.erp.meu-solutions.com/exam/result-speaking/:mockTestId
        writing: https://englishmaster.erp.meu-solutions.com/exam/result-writing/:mockTestId
        reading-listening: https://englishmaster.erp.meu-solutions.com/exam/result/:mockTestId
    show-more-topic: https://englishmaster.erp.meu-solutions.com/pack