spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://27.74.255.96:5431/english_master
    username: postgres
    password: meu@sds12@!#gh
  mail:
    port: 587
    host: smtp.gmail.com
    username: testmeusolution@gmail.com
    password: bopciqcccnuhoazn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: validate

englishmaster:
  salt:
    hash:
      jwtToken: AHFUI@fh31ofhq94g42o4ngjsdnfksdjnuhsnkajngqwiue2n@IUBFIBb1hf13
  jwtSecret: MeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolutionMeUSolution
  jwtExpiration: 259200000
  jwtRefreshExpirationMs: 259200000
  linkBE: http://localhost:8080/api/v2/
  linkFE: https://englishmaster.erp.meu-solutions.com/
  fileSave: D:\\\\Workplace\\\\FileEnglishMaster
  linkFileShowImageBE: https://gateway.dev.meu-solutions.com/englishmaster/api/v2/file/show/
  connect:
    student-nodejs: connect-student-nodejs.appspot.com

firebase:
  adminsdk:
    path: connect-student-nodejs-firebase-adminsdk-zo8a7-41168954b1.json

oxford:
  api:
    appId: b0d75c01
    appKey: b4c9785647f293f503eb45df46298c9d
    baseUrl: https://od-api.oxforddictionaries.com:443/api/v2

dictionary:
  api: https://api.dictionaryapi.dev/api/v2/entries/en
  file:
    path: english.txt

unsplash:
  api:
    key: s8Hd65PPMEIgtitVMXJJAcZzvVSiXI-q6qqx4M_PG7k

upload:
  server:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXQiOiJtZXVlbmdsaXNoIiwiaWF0IjoxNTE2MjM5MDIyfQ.jIAXLrrGhQseo8iZ6CNhXjf1Izs_nOK_RrcndzHYhJE18w0nPsx3PaHkG52zTARDWYasosOvTps_h_8-IAQ2FDZXgb2F5IhAukbDDEM7yL7bBtpZrgPnybbhu4TFcGMeealUvatifU1LUEKardPe62b12SdEiUkmag9lIjD81vBZ2KSAYJAFVchQ012dOPzT-O7qg2uBvfc-1XwKHBW5emMCEmlJh_DZ-rORSPvLpXzau9nhELAP9Hg-MCipmhhHR_4iaxX1ljhe4mq3T8rva86sLVDnOVzVB6I_Yl5S5zo2CCVM-5StxkAQABHtHzGeFsPYeHwK0ySwbYYHVF01lw
    api:
      upload: https://meuupload.meu-solutions.com/api/v1.0/upload/single/
      delete: https://meuupload.meu-solutions.com/api/v1.0/upload/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api/v2/v3/api-docs
    config-url: /api/v2/v3/api-docs/swagger-config
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

app:
  api:
    endpoint:
      prefix: /api/v2

cloudinary:
  cloud-name: dxioq4art
  api-key: 583938679842993
  api-secret: ZD545JfRsmG1wcwFwmOoN8VgcU0

gemini:
  api:
    endpoint: https://generativelanguage.googleapis.com/v1beta
    model: gemini-1.5-flash
    key: AIzaSyB9xoWwCHqniHln-KGcm6iA6qJ-awZdMgA